%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 29-Nov-2019 11:13:14

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "G2:I60";

% Specify column names and types
opts.VariableNames = ["Tiempo", "GDP", "TotalReserves"];
opts.SelectedVariableNames = ["Tiempo", "GDP", "TotalReserves"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
GobStats = readtable("C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

load('GDP.mat');
load('TotalReserves.mat');
