%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 28-Nov-2019 12:36:22

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "A2:G58";

% Specify column names and types
opts.VariableNames = ["IPC", "ImportComida", "ExportacionMercaderias", "Var4", "Var5", "Var6", "Tiempo"];
opts.SelectedVariableNames = ["IPC", "ImportComida", "ExportacionMercaderias", "Tiempo"];
opts.VariableTypes = ["double", "double", "double", "char", "char", "char", "double"];
opts = setvaropts(opts, [4, 5, 6], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [4, 5, 6], "EmptyFieldRule", "auto");

% Import the data
EcoStats = readtable("C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

load('Export.mat');
load('Import.mat');
load('IPC.mat');