%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 28-Nov-2019 13:03:46

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "D2:G56";

% Specify column names and types
opts.VariableNames = ["PoblacionUrbana", "Poblacionrural", "EmisionesdeCO2", "Tiempo"];
opts.SelectedVariableNames = ["PoblacionUrbana", "Poblacionrural", "EmisionesdeCO2", "Tiempo"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
CulStats = readtable("C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

load('CO2.mat');
load('PRural.mat');
load('PUrbana.mat');
