%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 29-Nov-2019 11:14:36

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "G37:J60";

% Specify column names and types
opts.VariableNames = ["Tiempo", "GDP", "TotalReserves", "GDDebt"];
opts.SelectedVariableNames = ["Tiempo", "GDP", "TotalReserves", "GDDebt"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
DebtStats = readtable("C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

load('GDP_Deuda.mat');
load('TotalReserves_Deuda.mat');
load('GDDebt.mat');