%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 02-Dec-2019 00:18:44

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "K2:N60";

% Specify column names and types
opts.VariableNames = ["TiempoE", "TiempoC", "TiempoG", "TiempoD"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
TimeStats = readtable("C:\Users\Hector\Documents\MATLAB\SpainStats.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

load('TiempoC.mat');
load('TiempoD.mat');
load('TiempoE.mat');
load('TiempoG.mat');
